services:
    purchase_platform.email.application_mailer:
        class: Purchase\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    purchase_platform.doctrine_listener.application_creation:
        class: Purchase\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@purchase_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
