<?php

namespace ADA\PurchaseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    //Récupère la somme de ticket déjà enregistrés suivant une date
    public function getTicketNumber($date)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('SUM(t.number)')
            ->where('t.date = :date')
            ->setParameter('date', $date);
        return $qb
            ->getQuery()
            ->getSingleScalarResult();
    }
}
