ada_purchase_index:
    path:      /
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:index
    
ada_purchase_ticketing:
    path:      /ticketing
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:ticketing

ada_purchase_date:
    path:      /ticketing/date
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:date

ada_purchase_summary:
    path:      /ticketing/summary
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:summary

ada_purchase_payment:
    path:      /ticketing/payment
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:payment

ada_purchase_final:
    path:      /ticketing/final
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:final

