ada_purchase_home:
    path:      /
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:index
    
ada_purchase_ticket:
    path:      /ticketing
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:ticket

ada_purchase_basket:
    path:      /ticketing/basket
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:basket

ada_purchase_translation:
    path:    /
    defaults:
        _controller: ADAPurchaseBundle:Ticketing:translation

