parameters:
    ada_purchase.reduce:  10
    ada_purchase.babyPrice: 0
    ada_purchase.ChildPrice: 8
    ada_purchase.SeniorPrice: 12
    ada_purchase.NormalPrice: 16

services:
    ada_purchase.sendMail:
        class: ADA\PurchaseBundle\Email\SendMail
        arguments:
            - "@mailer"
            - "@templating"
            - "@ada_purchase.barCodeManager"

    ada_purchase.sessionManager:
        class: ADA\PurchaseBundle\Session\SessionManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"

    ada_purchase.getAge:
            class: ADA\PurchaseBundle\Age\GetAge

    ada_purchase.priceManager:
        class: ADA\PurchaseBundle\Price\PriceManager
        arguments:
            - '@service_container'
            - ['%ada_purchase.reduce%']
            - ['%ada_purchase.babyPrice%']
            - ['%ada_purchase.ChildPrice%']
            - ['%ada_purchase.SeniorPrice%']
            - ['%ada_purchase.normalPrice%']

    ada_purchase.barCodeManager:
        class: ADA\PurchaseBundle\BarCode\BarCodeManager
        arguments:
            - "@ada_purchase.sessionManager"

    ada_purchase.barCodeManager_extension:
        class: ADA\PurchaseBundle\Twig\BarCodeManagerExtension
        arguments:
            - "@ada_purchase.barCodeManager"
        tags:
            - { name: twig.extension}

    ada_purchase.editManager:
        class: ADA\PurchaseBundle\Edit\EditManager
        arguments:
            - "@validator"