services:
    ada_purchase.email.application_mailer:
        class: ADA\PurchaseBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    ada_purchase.doctrine_listener.application_creation:
        class: ADA\PurchaseBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@ada_purchase.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
