services:
    ada_purchase.email.application_mailer:
        class: ADA\PurchaseBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
            - "@templating"

    ada_purchase.doctrine_listener.application_creation:
        class: ADA\PurchaseBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@ada_purchase.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ada_purchase.sessionManager:
        class: ADA\PurchaseBundle\Session\SessionManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"

    ada_purchase.priceManager:
        class: ADA\PurchaseBundle\Price\PriceManager
