services:
    ada_purchase.email.application_mailer:
        class: ADA\PurchaseBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
            - "@templating"
            - "@ada_purchase.barCodeManager"

    ada_purchase.doctrine_listener.application_creation:
        class: ADA\PurchaseBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@ada_purchase.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ada_purchase.sessionManager:
        class: ADA\PurchaseBundle\Session\SessionManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"

    ada_purchase.priceManager:
        class: ADA\PurchaseBundle\Price\PriceManager

    ada_purchase.barCodeManager:
            class: ADA\PurchaseBundle\BarCode\BarCodeManager

    ada_purchase.barCodeManager_extension:
                class: ADA\PurchaseBundle\Twig\BarCodeManagerExtension
                arguments:
                    - "@ada_purchase.barCodeManager"
                tags:
                    - { name: twig.extension}

    ada_purchase.validator.number:                              # Le nom du service
        class: ADA\PurchaseBundle\Validator\NumberValidator     # La classe du service, ici notre validateur déjà créé
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] # Les données qu'on injecte au service : la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: ada_purchase_number }  # C'est avec l'alias qu'on retrouvera le service
